# Generated by Django 5.0.2 on 2024-03-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_service', '0002_alter_plan_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='id',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='telegram_id',
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='chat_id',
            field=models.PositiveBigIntegerField(default=664935782, primary_key=True, serialize=False, unique=True),
        ),
    ]
