# Generated by Django 5.0.2 on 2024-02-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_service', '0003_alter_subscription_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='transaction_hash',
            field=models.CharField(default='0x', max_length=256, unique=True),
        ),
    ]
